# Generated by Django 4.0.8 on 2022-11-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomarker',
            name='exam',
            field=models.ManyToManyField(to='exams.exam'),
        ),
    ]
