# Generated by Django 4.0.8 on 2022-11-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_biomarker_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomarker',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
