# Generated by Django 4.0.8 on 2022-11-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_biomarker_short_name_alter_exam_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomarker',
            name='exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='biomarkers',
            field=models.ManyToManyField(related_name='exam', to='exams.biomarker'),
        ),
    ]
