# Generated by Django 4.0.8 on 2022-11-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_biomarker_exam_exam_biomarkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='biomarkers',
            field=models.ManyToManyField(blank=True, related_name='exam', to='exams.biomarker'),
        ),
    ]
